USE DBSHOPPING_CART
GO

CREATE PROC SP_CON_DashboardReport
AS
BEGIN
	SELECT
		(SELECT COUNT(*) FROM CLIENT) [ClientTotal],
		(SELECT ISNULL(SUM(Amount), 0) FROM SALE_DETAILS) [SaleTotal],
		(SELECT COUNT(*) FROM PRODUCT) [ProductTotal]
END
GO