CREATE DATABASE DBSHOPPING_CART
GO

USE DBSHOPPING_CART
GO

--Department
CREATE TABLE DEPARTMENT
(
DepartmentId TINYINT PRIMARY KEY NOT NULL
,D_description VARCHAR(40) NOT NULL
)
GO

--Town
CREATE TABLE TOWN
(
TownId SMALLINT PRIMARY KEY NOT NULL
,T_description VARCHAR(40) NOT NULL
,DepartmentId TINYINT FOREIGN KEY REFERENCES DEPARTMENT(DepartmentId)
)
GO

--Town location
CREATE TABLE TOWN_LOCATION
(
LocationId VARCHAR(20) PRIMARY KEY NOT NULL
,L_description VARCHAR(40)
,TownId SMALLINT FOREIGN KEY REFERENCES TOWN(TownId)
)
GO

--Category
CREATE TABLE CATEGORY
(
CategoryId INT PRIMARY KEY IDENTITY(1,1)
,C_description VARCHAR(100)
,Active BIT DEFAULT 1
,RegistrationDate DATETIME DEFAULT GETDATE()
)
GO

--Brand
CREATE TABLE BRAND
(
BrandId INT PRIMARY KEY IDENTITY(1,1)
,B_description VARCHAR(100)
,Active BIT DEFAULT 1
,RegistrationDate DATETIME DEFAULT GETDATE()
)
GO

--Product
CREATE TABLE PRODUCT
(
ProductId INT PRIMARY KEY IDENTITY(1,1)
,P_name VARCHAR(500)
,P_description VARCHAR(500)
,BrandId INT FOREIGN KEY REFERENCES BRAND(BrandId)
,CategoryId INT FOREIGN KEY REFERENCES CATEGORY(CategoryId)
,Price DECIMAL(10,2) DEFAULT 0
,Stock INT
,ImageRoute VARCHAR(100)
,ImageName VARCHAR(100)
,Active BIT DEFAULT 1
,RegistrationDate DATETIME DEFAULT GETDATE()
)
GO

--Client
CREATE TABLE CLIENT
(
ClientId INT PRIMARY KEY IDENTITY(1,1)
,C_name VARCHAR(50)
,C_surname VARCHAR(50)
,Email VARCHAR(100)
,Pass VARCHAR(150)
,IsReset BIT DEFAULT 0
,RegistrationDate DATETIME DEFAULT GETDATE()
)
GO

--Shopping cart
CREATE TABLE SHOPPING_CART
(
CartId INT PRIMARY KEY IDENTITY(1,1)
,ClientId INT FOREIGN KEY REFERENCES CLIENT(ClientId)
,ProductId INT FOREIGN KEY REFERENCES PRODUCT(ProductId)
,AMOUNT INT
)
GO

--Sale
CREATE TABLE SALE
(
SaleId INT PRIMARY KEY IDENTITY(1,1)
,ClientId INT FOREIGN KEY REFERENCES CLIENT(ClientId)
,ProductAmount INT
,Total DECIMAL(10,2)
,Contact VARCHAR(50)
,LocationId VARCHAR(20) FOREIGN KEY REFERENCES TOWN_LOCATION(LocationId)
,PhoneNumber VARCHAR(50)
,S_address VARCHAR(500)
,TransactionId VARCHAR(50)
,SaleDate DATETIME DEFAULT GETDATE()
)
GO

--Sale Details
CREATE TABLE SALE_DETAILS
(
Sale_detailsId INT PRIMARY KEY IDENTITY(1,1)
,SaleId INT FOREIGN KEY REFERENCES SALE(SaleId)
,ProductId INT FOREIGN KEY REFERENCES PRODUCT(ProductId)
,Amount INT
,Total DECIMAL(10,2)
)
GO

--User
CREATE TABLE APP_USER
(
UserId INT PRIMARY KEY IDENTITY(1,1)
,U_name VARCHAR(50)
,U_surname VARCHAR(50)
,Email VARCHAR(100)
,Pass VARCHAR(150)
,IsReset BIT DEFAULT 1
,Active BIT DEFAULT 1
,RegistrationDate DATETIME DEFAULT GETDATE()
)
GO