using System;
using System.Configuration;
using System.IO;
using System.Net;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Text;

namespace BusinessLayer
{
    public class BL_Resources
    {
        private static string emailSmtp = ConfigurationManager.AppSettings["EmailSmtp"].ToString();
        private static string passSmtp = ConfigurationManager.AppSettings["PassSmtp"].ToString();

        /// <summary>
        /// Method to generate a Random Password
        /// </summary>
        /// <returns></returns>
        public static string GeneratePass()
        {
            string pass = Guid.NewGuid().ToString("N").Substring(0, 6);
            return pass;
        }

        /// <summary>
        /// Method to encript text to SHA256
        /// </summary>
        /// <param name="text">Text to encrypt</param>
        /// <returns></returns>
        public static string Sha256Converter(string text)
        {
            StringBuilder sb = new StringBuilder();


            using (SHA256 hash = SHA256Managed.Create())
            {
                Encoding enc = Encoding.UTF8;
                byte[] result = hash.ComputeHash(enc.GetBytes(text));

                foreach(byte b in result)
                {
                    sb.Append(b.ToString("x2"));
                }
            }

            return sb.ToString();
        }

        /// <summary>
        /// Method that sends an email with the autogenerated password to the registered user
        /// </summary>
        /// <param name="email">Destination Email</param>
        /// <param name="subject">Subject message</param>
        /// <param name="message">Body message</param>
        /// <returns></returns>
        public static bool SendEmail(string email, string subject, string message)
        {
            bool result = false;

            try
            {
                MailMessage mail = new MailMessage();
                mail.To.Add(email);
                mail.From = new MailAddress(emailSmtp);
                mail.Subject = subject;
                mail.Body = message;
                mail.IsBodyHtml = true;

                var smtp = new SmtpClient()
                {
                    Credentials = new NetworkCredential(emailSmtp, passSmtp),
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true
                };

                smtp.Send(mail);
                result = true;
            }
            catch (Exception ex)
            {
                result = false;
            }

            return result;
        }

        /// <summary>
        /// Method that converts a file of given path if exists, in base64
        /// </summary>
        /// <param name="path">File path</param>
        /// <param name="successfulOp">Return parameter with boolean result of success operation</param>
        /// <returns></returns>
        public static string Base64Converter(string path, out bool successfulOp)
        {
            string base64Text = string.Empty;
            successfulOp = true;

            try
            {
                byte[] fileBytes = File.ReadAllBytes(path);
                base64Text = Convert.ToBase64String(fileBytes);
            }
            catch (Exception ex)
            {
                successfulOp = false;
            }

            return base64Text;
        }
    }
}
